export enum SchemaNames {
  ALBUM = 'album',
  BLACK_LIST = 'black_list',
  BLOG = 'blog',
  COMMENT = 'comment',
  FB_PAGES = 'facebook_pages',
  FILES = 'files',
  LANGUAGE = 'language',
  SKETCH_BOOK = 'sketch_book',
  SLIDER = 'slider',
  SUBS = 'subscribers',
  USERS = 'users',
  BIOGRAPHY = 'biography',
  YOUTUBE = 'youtube',
  PHOTOS = 'photos',
  LIKES = 'likes',
  LINKS = 'links',
  STREAMING = 'streaming',

  APP_SESSIONS = 'app_sessions',
  JOBS = 'jobs_queue',
  MIGRATIONS = 'app_update',
  BRUTE_FORCE = 'brute_force',
}
